In [2]:
import pandas as pd
import numpy as np

In [6]:
#lendo data frame do csv
df = pd.read_csv('cursos-prouni-a37448e1391540bdb72cf6787e381bb0.csv')
df.head()

,uf_busca,cidade_busca,universidade_nome,campus_nome,nome,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,AC,Acrelandia,Universidade Paulista - UNIP,ACRELANDIA - Centro,Administração,Bacharelado,Curso a Distância,289.0,1.0,1.0,NaN,NaN,572.74,548.0,NaN,NaN
1,AC,Cruzeiro do Sul,Centro Universitário Internacional - Uninter -...,PAP CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,298.0,1.0,NaN,NaN,NaN,646.14,NaN,NaN,NaN
2,AC,Cruzeiro do Sul,Faculdade Educacional da Lapa - FAEL,AC - CRUZEIRO DO SUL - POLO EAD - CENTRO,Administração,Bacharelado,Curso a Distância,325.0,NaN,NaN,1.0,NaN,NaN,NaN,577.62,NaN
3,AC,Cruzeiro do Sul,Universidade Paulista - UNIP,CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,319.0,1.0,NaN,NaN,NaN,616.68,NaN,NaN,NaN
4,AC,Rio Branco,Centro Universitário Internacional - Uninter -...,PAP RIO BRANCO - Bosque,Administração,Bacharelado,Curso a Distância,298.0,NaN,NaN,1.0,NaN,NaN,NaN,569.00,NaN

In [17]:
df.groupby('uf_busca').mensalidade.mean().sort_values()

uf_busca
RR    428.599910
MS    461.716115
MT    491.546548
PA    518.926445
AL    534.481284
GO    557.586455
SC    560.686606
AC    570.743645
AM    576.651958
AP    578.471918
TO    588.325948
SP    591.408001
PR    602.332657
ES    621.275855
PI    629.500938
PE    635.090427
BA    639.848802
SE    642.081424
RO    661.994514
DF    666.951063
MG    668.955401
RN    679.597690
PB    696.574027
MA    728.632607
RS    743.003467
RJ    745.488377
CE    801.654853
Name: mensalidade, dtype: float64

In [23]:
#verifica colunas com itens nulos e mostra a soma de quantos itens nulos tem
df.isnull().sum()

uf_busca                    0
cidade_busca                0
universidade_nome           0
campus_nome                 0
nome                        0
grau                        0
turno                       0
mensalidade                 0
bolsa_integral_cotas     8927
bolsa_integral_ampla    16043
bolsa_parcial_cotas     32619
bolsa_parcial_ampla     28406
nota_integral_ampla      8927
nota_integral_cotas     24645
nota_parcial_ampla      25097
nota_parcial_cotas      35928
dtype: int64

In [25]:
df[df.nota_parcial_cotas.isnull()]

,uf_busca,cidade_busca,universidade_nome,campus_nome,nome,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,AC,Acrelandia,Universidade Paulista - UNIP,ACRELANDIA - Centro,Administração,Bacharelado,Curso a Distância,289.00,1.0,1.0,NaN,NaN,572.74,548.00,NaN,NaN
1,AC,Cruzeiro do Sul,Centro Universitário Internacional - Uninter -...,PAP CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,298.00,1.0,NaN,NaN,NaN,646.14,NaN,NaN,NaN
2,AC,Cruzeiro do Sul,Faculdade Educacional da Lapa - FAEL,AC - CRUZEIRO DO SUL - POLO EAD - CENTRO,Administração,Bacharelado,Curso a Distância,325.00,NaN,NaN,1.0,NaN,NaN,NaN,577.62,NaN
3,AC,Cruzeiro do Sul,Universidade Paulista - UNIP,CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,319.00,1.0,NaN,NaN,NaN,616.68,NaN,NaN,NaN
4,AC,Rio Branco,Centro Universitário Internacional - Uninter -...,PAP RIO BRANCO - Bosque,Administração,Bacharelado,Curso a Distância,298.00,NaN,NaN,1.0,NaN,NaN,NaN,569.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41440,MS,Campo Grande,Universidade Católica Dom Bosco - UCDB,CAMPO GRANDE - Jardim Seminário,Zootecnia,Bacharelado,Matutino,1107.00,1.0,1.0,NaN,NaN,624.76,597.42,NaN,NaN
41442,PA,Redencao,Faculdade de Ensino Superior da Amazônia Reuni...,POLO NA SEDE - ALTO PARANÁ,Zootecnia,Bacharelado,Noturno,932.83,3.0,1.0,NaN,NaN,634.46,578.50,NaN,NaN
41444,SC,Xanxere,Universidade do Oeste de Santa Catarina - UNOESC,CAMPUS DE XANXERÊ - Jardim Tarumã,Zootecnia,Bacharelado,Noturno,1298.00,0.0,2.0,NaN,2.0,590.42,NaN,537.46,NaN
41445,SP,Barretos,Centro Universitário da Fundação Educacional d...,CAMPUS - BARRETOS - AEROPORTO/MARIETA - Aerop...,Zootecnia,Bacharelado,Integral,1222.66,2.0,3.0,NaN,20.0,604.00,587.50,517.40,NaN
41446,SP,Presidente Prudente,Universidade do Oeste Paulista - UNOESTE,CAMPUS II - LIMOEIRO,Zootecnia,Bacharelado,Noturno,1340.00,0.0,8.0,NaN,NaN,597.58,NaN,NaN,NaN