# Tratando um dataset, sobre os passageiros do titanic, apartir de um csv, sem utilizar pandas ou outra biblioteca de analise de dados

In [1]:
#Abrindo e lendo o dataset titanic.csv
titanic_csv = open('titanic.csv','r')

lines = titanic_csv.readlines()

In [2]:
#fechando conexão com o arquivo de leitura
titanic_csv.close()

In [3]:
#salvando em "header" apenas o cabeçalho do arquivo separado por virgula

header = lines[0].split(',')

print(header)

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked\n']

In [4]:
#visualizando padrão do nome ("sobrenome, nome")
lines[1]

'1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S\n'

In [5]:
#tratando os nomes no padrão norte americano 
#para o padrão Pt-br usando a biblioteca regex
import re

def treatName(line):
    match = re.compile(r'"(.*)(,)(\s)(.*)"')
    return match.sub(r'"\4 \1"', line)

#visualizando padrão do nome ("nome sobrenome")
treatName(lines[1])

'1,0,3,"Mr. Owen Harris Braund",male,22,1,0,A/5 21171,7.25,,S\n'

In [6]:
#criando um dicionário com o cabeçalho e abrindo lista para info dos passageiros
titanicInfo = {}
for head in header:
    titanicInfo[head] = []
titanicInfo

{'PassengerId': [],
 'Survived': [],
 'Pclass': [],
 'Name': [],
 'Sex': [],
 'Age': [],
 'SibSp': [],
 'Parch': [],
 'Ticket': [],
 'Fare': [],
 'Cabin': [],
 'Embarked\n': []}

In [7]:
#criando uma lista com os dados separados por virgula
dataList = []
for data in lines[1:]:
    splitedLine = treatName(data).split(',')
    dataList.append(splitedLine)
    
dataList

[['1',
  '0',
  '3',
  '"Mr. Owen Harris Braund"',
  'male',
  '22',
  '1',
  '0',
  'A/5 21171',
  '7.25',
  '',
  'S\n'],
 ['2',
  '1',
  '1',
  '"Mrs. John Bradley (Florence Briggs Thayer) Cumings"',
  'female',
  '38',
  '1',
  '0',
  'PC 17599',
  '71.2833',
  'C85',
  'C\n'],
 ['3',
  '1',
  '3',
  '"Miss. Laina Heikkinen"',
  'female',
  '26',
  '0',
  '0',
  'STON/O2. 3101282',
  '7.925',
  '',
  'S\n'],
 ['4',
  '1',
  '1',
  '"Mrs. Jacques Heath (Lily May Peel) Futrelle"',
  'female',
  '35',
  '1',
  '0',
  '113803',
  '53.1',
  'C123',
  'S\n'],
 ['5',
  '0',
  '3',
  '"Mr. William Henry Allen"',
  'male',
  '35',
  '0',
  '0',
  '373450',
  '8.05',
  '',
  'S\n'],
 ['6',
  '0',
  '3',
  '"Mr. James Moran"',
  'male',
  '',
  '0',
  '0',
  '330877',
  '8.4583',
  '',
  'Q\n'],
 ['7',
  '0',
  '1',
  '"Mr. Timothy J McCarthy"',
  'male',
  '54',
  '0',
  '0',
  '17463',
  '51.8625',
  'E46',
  'S\n'],
 ['8',
  '0',
  '3',
  '"Master. Gosta Leonard Palsson"',
  'male',
  '2',
  '3',
  '1',
  '349909',
  '21.075',
  '',
  'S\n'],
 ['9',
  '1',
  '3',
  '"Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson"',
  'female',
  '27',
  '0',
  '2',
  '347742',
  '11.1333',
  '',
  'S\n'],
 ['10',
  '1',
  '2',
  '"Mrs. Nicholas (Adele Achem) Nasser"',
  'female',
  '14',
  '1',
  '0',
  '237736',
  '30.0708',
  '',
  'C\n'],
 ['11',
  '1',
  '3',
  '"Miss. Marguerite Rut Sandstrom"',
  'female',
  '4',
  '1',
  '1',
  'PP 9549',
  '16.7',
  'G6',
  'S\n'],
 ['12',
  '1',
  '1',
  '"Miss. Elizabeth Bonnell"',
  'female',
  '58',
  '0',
  '0',
  '113783',
  '26.55',
  'C103',
  'S\n'],
 ['13',
  '0',
  '3',
  '"Mr. William Henry Saundercock"',
  'male',
  '20',
  '0',
  '0',
  'A/5. 2151',
  '8.05',
  '',
  'S\n'],
 ['14',
  '0',
  '3',
  '"Mr. Anders Johan Andersson"',
  'male',
  '39',
  '1',
  '5',
  '347082',
  '31.275',
  '',
  'S\n'],
 ['15',
  '0',
  '3',
  '"Miss. Hulda Amanda Adolfina Vestrom"',
  'female',
  '14',
  '0',
  '0',
  '350406',
  '7.8542',
  '',
  'S\n'],
 ['16',
  '1',
  '2',
  '"Mrs. (Mary D Kingcome)  Hewlett"',
  'female',
  '55',
  '0',
  '0',
  '248706',
  '16',
  '',
  'S\n'],
 ['17',
  '0',
  '3',
  '"Master. Eugene Rice"',
  'male',
  '2',
  '4',
  '1',
  '382652',
  '29.125',
  '',
  'Q\n'],
 ['18',
  '1',
  '2',
  '"Mr. Charles Eugene Williams"',
  'male',
  '',
  '0',
  '0',
  '244373',
  '13',
  '',
  'S\n'],
 ['19',
  '0',
  '3',
  '"Mrs. Julius (Emelia Maria Vandemoortele) Vander Planke"',
  'female',
  '31',
  '1',
  '0',
  '345763',
  '18',
  '',
  'S\n'],
 ['20',
  '1',
  '3',
  '"Mrs. Fatima Masselmani"',
  'female',
  '',
  '0',
  '0',
  '2649',
  '7.225',
  '',
  'C\n'],
 ['21',
  '0',
  '2',
  '"Mr. Joseph J Fynney"',
  'male',
  '35',
  '0',
  '0',
  '239865',
  '26',
  '',
  'S\n'],
 ['22',
  '1',
  '2',
  '"Mr. Lawrence Beesley"',
  'male',
  '34',
  '0',
  '0',
  '248698',
  '13',
  'D56',
  'S\n'],
 ['23',
  '1',
  '3',
  '"Miss. Anna "Annie" McGowan"',
  'female',
  '15',
  '0',
  '0',
  '330923',
  '8.0292',
  '',
  'Q\n'],
 ['24',
  '1',
  '1',
  '"Mr. William Thompson Sloper"',
  'male',
  '28',
  '0',
  '0',
  '113788',
  '35.5',
  'A6',
  'S\n'],
 ['25',
  '0',
  '3',
  '"Miss. Torborg Danira Palsson"',
  'female',
  '8',
  '3',
  '1',
  '349909',
  '21.075',
  '',
  'S\n'],
 ['26',
  '1',
  '3',
  '"Mrs. Carl Oscar (Selma Augusta Emilia Johansson) Asplund"',
  'female',
  '38',
  '1',
  '5',
  '347077',
  '31.3875',
  '',
  'S\n'],
 ['27',
  '0',
  '3',
  '"Mr. Farred Chehab Emir"',
  'male',
  '',
  '0',
  '0',
  '2631',
  '7.225',
  '',
  'C\n'],
 ['28',
  '0',
  '1',
  '"Mr. Charles Alexander Fortune"',
  'male',
  '19',
  '3',
  '2',
  '19950',
  '263',
  'C23 C25 C27',
  'S\n'],
 ['29',
  '1',
  '3',
  '"Miss. Ellen "Nellie" O\'Dwyer"',
  'female',
  '',
  '0',
  '0',
  '330959',
  '7.8792',
  '',
  'Q\n'],
 ['30',
  '0',
  '3',
  '"Mr. Lalio Todoroff"',
  'male',
  '',
  '0',
  '0',
  '349216',
  '7.8958',
  '',
  'S\n'],
 ['31',
  '0',
  '1',
  '"Don. Manuel E Uruchurtu"',
  'male',
  '40',
  '0',
  '0',
  'PC 17601',
  '27.7208',
  '',
  'C\n'],
 ['32',
  '1',
  '1',
  '"Mrs. William Augustus (Marie Eugenie) Spencer"',
  'female',
  '',
  '1',
  '0',
  'PC 17569',
  '146.5208',
  'B78',
  'C\n'],
 ['33',
  '1',
  '3',
  '"Miss. Mary Agatha Glynn"',
  'female',
  '',
  '0',
  '0',
  '335677',
  '7.75',
  '',
  'Q\n'],
 ['34',
  '0',
  '2',
  '"Mr. Edward H Wheadon"',
  'male',
  '66',
  '0',
  '0',
  'C.A. 24579',
  '10.5',
  '',
  'S\n'],
 ['35',
  '0',
  '1',
  '"Mr. Edgar Joseph Meyer"',
  'male',
  '28',
  '1',
  '0',
  'PC 17604',
  '82.1708',
  '',
  'C\n'],
 ['36',
  '0',
  '1',
  '"Mr. Alexander Oskar Holverson"',
  'male',
  '42',
  '1',
  '0',
  '113789',
  '52',
  '',
  'S\n'],
 ['37',
  '1',
  '3',
  '"Mr. Hanna Mamee"',
  'male',
  '',
  '0',
  '0',
  '2677',
  '7.2292',
  '',
  'C\n'],
 ['38',
  '0',
  '3',
  '"Mr. Ernest Charles Cann"',
  'male',
  '21',
  '0',
  '0',
  'A./5. 2152',
  '8.05',
  '',
  'S\n'],
 ['39',
  '0',
  '3',
  '"Miss. Augusta Maria Vander Planke"',
  'female',
  '18',
  '2',
  '0',
  '345764',
  '18',
  '',
  'S\n'],
 ['40',
  '1',
  '3',
  '"Miss. Jamila Nicola-Yarred"',
  'female',
  '14',
  '1',
  '0',
  '2651',
  '11.2417',
  '',
  'C\n'],
 ['41',
  '0',
  '3',
  '"Mrs. Johan (Johanna Persdotter Larsson) Ahlin"',
  'female',
  '40',
  '1',
  '0',
  '7546',
  '9.475',
  '',
  'S\n'],
 ['42',
  '0',
  '2',
  '"Mrs. William John Robert (Dorothy Ann Wonnacott) Turpin"',
  'female',
  '27',
  '1',
  '0',
  '11668',
  '21',
  '',
  'S\n'],
 ['43',
  '0',
  '3',
  '"Mr. Theodor Kraeff"',
  'male',
  '',
  '0',
  '0',
  '349253',
  '7.8958',
  '',
  'C\n'],
 ['44',
  '1',
  '2',
  '"Miss. Simonne Marie Anne Andree Laroche"',
  'female',
  '3',
  '1',
  '2',
  'SC/Paris 2123',
  '41.5792',
  '',
  'C\n'],
 ['45',
  '1',
  '3',
  '"Miss. Margaret Delia Devaney"',
  'female',
  '19',
  '0',
  '0',
  '330958',
  '7.8792',
  '',
  'Q\n'],
 ['46',
  '0',
  '3',
  '"Mr. William John Rogers"',
  'male',
  '',
  '0',
  '0',
  'S.C./A.4. 23567',
  '8.05',
  '',
  'S\n'],
 ['47',
  '0',
  '3',
  '"Mr. Denis Lennon"',
  'male',
  '',
  '1',
  '0',
  '370371',
  '15.5',
  '',
  'Q\n'],
 ['48',
  '1',
  '3',
  '"Miss. Bridget O\'Driscoll"',
  'female',
  '',
  '0',
  '0',
  '14311',
  '7.75',
  '',
  'Q\n'],
 ['49',
  '0',
  '3',
  '"Mr. Youssef Samaan"',
  'male',
  '',
  '2',
  '0',
  '2662',
  '21.6792',
  '',
  'C\n'],
 ['50',
  '0',
  '3',
  '"Mrs. Josef (Josefine Franchi) Arnold-Franchi"',
  'female',
  '18',
  '1',
  '0',
  '349237',
  '17.8',
  '',
  'S\n'],
 ['51',
  '0',
  '3',
  '"Master. Juha Niilo Panula"',
  'male',
  '7',
  '4',
  '1',
  '3101295',
  '39.6875',
  '',
  'S\n'],
 ['52',
  '0',
  '3',
  '"Mr. Richard Cater Nosworthy"',
  'male',
  '21',
  '0',
  '0',
  'A/4. 39886',
  '7.8',
  '',
  'S\n'],
 ['53',
  '1',
  '1',
  '"Mrs. Henry Sleeper (Myna Haxtun) Harper"',
  'female',
  '49',
  '1',
  '0',
  'PC 17572',
  '76.7292',
  'D33',
  'C\n'],
 ['54',
  '1',
  '2',
  '"Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe"',
  'female',
  '29',
  '1',
  '0',
  '2926',
  '26',
  '',
  'S\n'],
 ['55',
  '0',
  '1',
  '"Mr. Engelhart Cornelius Ostby"',
  'male',
  '65',
  '0',
  '1',
  '113509',
  '61.9792',
  'B30',
  'C\n'],
 ['56',
  '1',
  '1',
  '"Mr. Hugh Woolner"',
  'male',
  '',
  '0',
  '0',
  '19947',
  '35.5',
  'C52',
  'S\n'],
 ['57',
  '1',
  '2',
  '"Miss. Emily Rugg"',
  'female',
  '21',
  '0',
  '0',
  'C.A. 31026',
  '10.5',
  '',
  'S\n'],
 ['58',
  '0',
  '3',
  '"Mr. Mansouer Novel"',
  'male',
  '28.5',
  '0',
  '0',
  '2697',
  '7.2292',
  '',
  'C\n'],
 ['59',
  '1',
  '2',
  '"Miss. Constance Mirium West"',
  'female',
  '5',
  '1',
  '2',
  'C.A. 34651',
  '27.75',
  '',
  'S\n'],
 ['60',
  '0',
  '3',
  '"Master. William Frederick Goodwin"',
  'male',
  '11',
  '5',
  '2',
  'CA 2144',
  '46.9',
  '',
  'S\n'],
 ['61',
  '0',
  '3',
  '"Mr. Orsen Sirayanian"',
  'male',
  '22',
  '0',
  '0',
  '2669',
  '7.2292',
  '',
  'C\n'],
 ['62',
  '1',
  '1',
  '"Miss. Amelie Icard"',
  'female',
  '38',
  '0',
  '0',
  '113572',
  '80',
  'B28',
  '\n'],
 ['63',
  '0',
  '1',
  '"Mr. Henry Birkhardt Harris"',
  'male',
  '45',
  '1',
  '0',
  '36973',
  '83.475',
  'C83',
  'S\n'],
 ['64',
  '0',
  '3',
  '"Master. Harald Skoog"',
  'male',
  '4',
  '3',
  '2',
  '347088',
  '27.9',
  '',
  'S\n'],
 ['65',
  '0',
  '1',
  '"Mr. Albert A Stewart"',
  'male',
  '',
  '0',
  '0',
  'PC 17605',
  '27.7208',
  '',
  'C\n'],
 ['66',
  '1',
  '3',
  '"Master. Gerios Moubarek"',
  'male',
  '',
  '1',
  '1',
  '2661',
  '15.2458',
  '',
  'C\n'],
 ['67',
  '1',
  '2',
  '"Mrs. (Elizabeth Ramell) Nye"',
  'female',
  '29',
  '0',
  '0',
  'C.A. 29395',
  '10.5',
  'F33',
  'S\n'],
 ['68',
  '0',
  '3',
  '"Mr. Ernest James Crease"',
  'male',
  '19',
  '0',
  '0',
  'S.P. 3464',
  '8.1583',
  '',
  'S\n'],
 ['69',
  '1',
  '3',
  '"Miss. Erna Alexandra Andersson"',
  'female',
  '17',
  '4',
  '2',
  '3101281',
  '7.925',
  '',
  'S\n'],
 ['70',
  '0',
  '3',
  '"Mr. Vincenz Kink"',
  'male',
  '26',
  '2',
  '0',
  '315151',
  '8.6625',
  '',
  'S\n'],
 ['71',
  '0',
  '2',
  '"Mr. Stephen Curnow Jenkin"',
  'male',
  '32',
  '0',
  '0',
  'C.A. 33111',
  '10.5',
  '',
  'S\n'],
 ['72',
  '0',
  '3',
  '"Miss. Lillian Amy Goodwin"',
  'female',
  '16',
  '5',
  '2',
  'CA 2144',
  '46.9',
  '',
  'S\n'],
 ['73',
  '0',
  '2',
  '"Mr. Ambrose Jr Hood"',
  'male',
  '21',
  '0',
  '0',
  'S.O.C. 14879',
  '73.5',
  '',
  'S\n'],
 ['74',
  '0',
  '3',
  '"Mr. Apostolos Chronopoulos"',
  'male',
  '26',
  '1',
  '0',
  '2680',
  '14.4542',
  '',
  'C\n'],
 ['75',
  '1',
  '3',
  '"Mr. Lee Bing"',
  'male',
  '32',
  '0',
  '0',
  '1601',
  '56.4958',
  '',
  'S\n'],
 ['76',
  '0',
  '3',
  '"Mr. Sigurd Hansen Moen"',
  'male',
  '25',
  '0',
  '0',
  '348123',
  '7.65',
  'F G73',
  'S\n'],
 ['77',
  '0',
  '3',
  '"Mr. Ivan Staneff"',
  'male',
  '',
  '0',
  '0',
  '349208',
  '7.8958',
  '',
  'S\n'],
 ['78',
  '0',
  '3',
  '"Mr. Rahamin Haim Moutal"',
  'male',
  '',
  '0',
  '0',
  '374746',
  '8.05',
  '',
  'S\n'],
 ['79',
  '1',
  '2',
  '"Master. Alden Gates Caldwell"',
  'male',
  '0.83',
  '0',
  '2',
  '248738',
  '29',
  '',
  'S\n'],
 ['80',
  '1',
  '3',
  '"Miss. Elizabeth Dowdell"',
  'female',
  '30',
  '0',
  '0',
  '364516',
  '12.475',
  '',
  'S\n'],
 ['81',
  '0',
  '3',
  '"Mr. Achille Waelens"',
  'male',
  '22',
  '0',
  '0',
  '345767',
  '9',
  '',
  'S\n'],
 ['82',
  '1',
  '3',
  '"Mr. Jan Baptist Sheerlinck"',
  'male',
  '29',
  '0',
  '0',
  '345779',
  '9.5',
  '',
  'S\n'],
 ['83',
  '1',
  '3',
  '"Miss. Brigdet Delia McDermott"',
  'female',
  '',
  '0',
  '0',
  '330932',
  '7.7875',
  '',
  'Q\n'],
 ['84',
  '0',
  '1',
  '"Mr. Francisco M Carrau"',
  'male',
  '28',
  '0',
  '0',
  '113059',
  '47.1',
  '',
  'S\n'],
 ['85',
  '1',
  '2',
  '"Miss. Bertha Ilett"',
  'female',
  '17',
  '0',
  '0',
  'SO/C 14885',
  '10.5',
  '',
  'S\n'],
 ['86',
  '1',
  '3',
  '"Mrs. Karl Alfred (Maria Mathilda Gustafsson) Backstrom"',
  'female',
  '33',
  '3',
  '0',
  '3101278',
  '15.85',
  '',
  'S\n'],
 ['87',
  '0',
  '3',
  '"Mr. William Neal Ford"',
  'male',
  '16',
  '1',
  '3',
  'W./C. 6608',
  '34.375',
  '',
  'S\n'],
 ['88',
  '0',
  '3',
  '"Mr. Selman Francis Slocovski"',
  'male',
  '',
  '0',
  '0',
  'SOTON/OQ 392086',
  '8.05',
  '',
  'S\n'],
 ['89',
  '1',
  '1',
  '"Miss. Mabel Helen Fortune"',
  'female',
  '23',
  '3',
  '2',
  '19950',
  '263',
  'C23 C25 C27',
  'S\n'],
 ['90',
  '0',
  '3',
  '"Mr. Francesco Celotti"',
  'male',
  '24',
  '0',
  '0',
  '343275',
  '8.05',
  '',
  'S\n'],
 ['91',
  '0',
  '3',
  '"Mr. Emil Christmann"',
  'male',
  '29',
  '0',
  '0',
  '343276',
  '8.05',
  '',
  'S\n'],
 ['92',
  '0',
  '3',
  '"Mr. Paul Edvin Andreasson"',
  'male',
  '20',
  '0',
  '0',
  '347466',
  '7.8542',
  '',
  'S\n'],
 ['93',
  '0',
  '1',
  '"Mr. Herbert Fuller Chaffee"',
  'male',
  '46',
  '1',
  '0',
  'W.E.P. 5734',
  '61.175',
  'E31',
  'S\n'],
 ['94',
  '0',
  '3',
  '"Mr. Bertram Frank Dean"',
  'male',
  '26',
  '1',
  '2',
  'C.A. 2315',
  '20.575',
  '',
  'S\n'],
 ['95',
  '0',
  '3',
  '"Mr. Daniel Coxon"',
  'male',
  '59',
  '0',
  '0',
  '364500',
  '7.25',
  '',
  'S\n'],
 ['96',
  '0',
  '3',
  '"Mr. Charles Joseph Shorney"',
  'male',
  '',
  '0',
  '0',
  '374910',
  '8.05',
  '',
  'S\n'],
 ['97',
  '0',
  '1',
  '"Mr. George B Goldschmidt"',
  'male',
  '71',
  '0',
  '0',
  'PC 17754',
  '34.6542',
  'A5',
  'C\n'],
 ['98',
  '1',
  '1',
  '"Mr. William Bertram Greenfield"',
  'male',
  '23',
  '0',
  '1',
  'PC 17759',
  '63.3583',
  'D10 D12',
  'C\n'],
 ['99',
  '1',
  '2',
  '"Mrs. John T (Ada Julia Bone) Doling"',
  'female',
  '34',
  '0',
  '1',
  '231919',
  '23',
  '',
  'S\n'],
 ['100',
  '0',
  '2',
  '"Mr. Sinai Kantor"',
  'male',
  '34',
  '1',
  '0',
  '244367',
  '26',
  '',
  'S\n'],
 ['101',
  '0',
  '3',
  '"Miss. Matilda Petranec"',
  'female',
  '28',
  '0',
  '0',
  '349245',
  '7.8958',
  '',
  'S\n'],
 ['102',
  '0',
  '3',
  '"Mr. Pastcho ("Pentcho") Petroff"',
  'male',
  '',
  '0',
  '0',
  '349215',
  '7.8958',
  '',
  'S\n'],
 ['103',
  '0',
  '1',
  '"Mr. Richard Frasar White"',
  'male',
  '21',
  '0',
  '1',
  '35281',
  '77.2875',
  'D26',
  'S\n'],
 ['104',
  '0',
  '3',
  '"Mr. Gustaf Joel Johansson"',
  'male',
  '33',
  '0',
  '0',
  '7540',
  '8.6542',
  '',
  'S\n'],
 ['105',
  '0',
  '3',
  '"Mr. Anders Vilhelm Gustafsson"',
  'male',
  '37',
  '2',
  '0',
  '3101276',
  '7.925',
  '',
  'S\n'],
 ['106',
  '0',
  '3',
  '"Mr. Stoytcho Mionoff"',
  'male',
  '28',
  '0',
  '0',
  '349207',
  '7.8958',
  '',
  'S\n'],
 ['107',
  '1',
  '3',
  '"Miss. Anna Kristine Salkjelsvik"',
  'female',
  '21',
  '0',
  '0',
  '343120',
  '7.65',
  '',
  'S\n'],
 ['108',
  '1',
  '3',
  '"Mr. Albert Johan Moss"',
  'male',
  '',
  '0',
  '0',
  '312991',
  '7.775',
  '',
  'S\n'],
 ['109',
  '0',
  '3',
  '"Mr. Tido Rekic"',
  'male',
  '38',
  '0',
  '0',
  '349249',
  '7.8958',
  '',
  'S\n'],
 ['110',
  '1',
  '3',
  '"Miss. Bertha Moran"',
  'female',
  '',
  '1',
  '0',
  '371110',
  '24.15',
  '',
  'Q\n'],
 ['111',
  '0',
  '1',
  '"Mr. Walter Chamberlain Porter"',
  'male',
  '47',
  '0',
  '0',
  '110465',
  '52',
  'C110',
  'S\n'],
 ['112',
  '0',
  '3',
  '"Miss. Hileni Zabour"',
  'female',
  '14.5',
  '1',
  '0',
  '2665',
  '14.4542',
  '',
  'C\n'],
 ['113',
  '0',
  '3',
  '"Mr. David John Barton"',
  'male',
  '22',
  '0',
  '0',
  '324669',
  '8.05',
  '',
  'S\n'],
 ['114',
  '0',
  '3',
  '"Miss. Katriina Jussila"',
  'female',
  '20',
  '1',
  '0',
  '4136',
  '9.825',
  '',
  'S\n'],
 ['115',
  '0',
  '3',
  '"Miss. Malake Attalah"',
  'female',
  '17',
  '0',
  '0',
  '2627',
  '14.4583',
  '',
  'C\n'],
 ['116',
  '0',
  '3',
  '"Mr. Edvard Pekoniemi"',
  'male',
  '21',
  '0',
  '0',
  'STON/O 2. 3101294',
  '7.925',
  '',
  'S\n'],
 ['117',
  '0',
  '3',
  '"Mr. Patrick Connors"',
  'male',
  '70.5',
  '0',
  '0',
  '370369',
  '7.75',
  '',
  'Q\n'],
 ['118',
  '0',
  '2',
  '"Mr. William John Robert Turpin"',
  'male',
  '29',
  '1',
  '0',
  '11668',
  '21',
  '',
  'S\n'],
 ['119',
  '0',
  '1',
  '"Mr. Quigg Edmond Baxter"',
  'male',
  '24',
  '0',
  '1',
  'PC 17558',
  '247.5208',
  'B58 B60',
  'C\n'],
 ['120',
  '0',
  '3',
  '"Miss. Ellis Anna Maria Andersson"',
  'female',
  '2',
  '4',
  '2',
  '347082',
  '31.275',
  '',
  'S\n'],
 ['121',
  '0',
  '2',
  '"Mr. Stanley George Hickman"',
  'male',
  '21',
  '2',
  '0',
  'S.O.C. 14879',
  '73.5',
  '',
  'S\n'],
 ['122',
  '0',
  '3',
  '"Mr. Leonard Charles Moore"',
  'male',
  '',
  '0',
  '0',
  'A4. 54510',
  '8.05',
  '',
  'S\n'],
 ['123',
  '0',
  '2',
  '"Mr. Nicholas Nasser"',
  'male',
  '32.5',
  '1',
  '0',
  '237736',
  '30.0708',
  '',
  'C\n'],
 ['124',
  '1',
  '2',
  '"Miss. Susan Webber"',
  'female',
  '32.5',
  '0',
  '0',
  '27267',
  '13',
  'E101',
  'S\n'],
 ['125',
  '0',
  '1',
  '"Mr. Percival Wayland White"',
  'male',
  '54',
  '0',
  '1',
  '35281',
  '77.2875',
  'D26',
  'S\n'],
 ['126',
  '1',
  '3',
  '"Master. Elias Nicola-Yarred"',
  'male',
  '12',
  '1',
  '0',
  '2651',
  '11.2417',
  '',
  'C\n'],
 ['127',
  '0',
  '3',
  '"Mr. Martin McMahon"',
  'male',
  '',
  '0',
  '0',
  '370372',
  '7.75',
  '',
  'Q\n'],
 ['128',
  '1',
  '3',
  '"Mr. Fridtjof Arne Madsen"',
  'male',
  '24',
  '0',
  '0',
  'C 17369',
  '7.1417',
  '',
  'S\n'],
 ['129',
  '1',
  '3',
  '"Miss. Anna Peter"',
  'female',
  '',
  '1',
  '1',
  '2668',
  '22.3583',
  'F E69',
  'C\n'],
 ['130',
  '0',
  '3',
  '"Mr. Johan Ekstrom"',
  'male',
  '45',
  '0',
  '0',
  '347061',
  '6.975',
  '',
  'S\n'],
 ['131',
  '0',
  '3',
  '"Mr. Jozef Drazenoic"',
  'male',
  '33',
  '0',
  '0',
  '349241',
  '7.8958',
  '',
  'C\n'],
 ['132',
  '0',
  '3',
  '"Mr. Domingos Fernandeo Coelho"',
  'male',
  '20',
  '0',
  '0',
  'SOTON/O.Q. 3101307',
  '7.05',
  '',
  'S\n'],
 ['133',
  '0',
  '3',
  '"Mrs. Alexander A (Grace Charity Laury) Robins"',
  'female',
  '47',
  '1',
  '0',
  'A/5. 3337',
  '14.5',
  '',
  'S\n'],
 ['134',
  '1',
  '2',
  '"Mrs. Leopold (Mathilde Francoise Pede) Weisz"',
  'female',
  '29',
  '1',
  '0',
  '228414',
  '26',
  '',
  'S\n'],
 ['135',
  '0',
  '2',
  '"Mr. Samuel James Hayden Sobey"',
  'male',
  '25',
  '0',
  '0',
  'C.A. 29178',
  '13',
  '',
  'S\n'],
 ['136',
  '0',
  '2',
  '"Mr. Emile Richard"',
  'male',
  '23',
  '0',
  '0',
  'SC/PARIS 2133',
  '15.0458',
  '',
  'C\n'],
 ['137',
  '1',
  '1',
  '"Miss. Helen Monypeny Newsom"',
  'female',
  '19',
  '0',
  '2',
  '11752',
  '26.2833',
  'D47',
  'S\n'],
 ['138',
  '0',
  '1',
  '"Mr. Jacques Heath Futrelle"',
  'male',
  '37',
  '1',
  '0',
  '113803',
  '53.1',
  'C123',
  'S\n'],
 ['139',
  '0',
  '3',
  '"Mr. Olaf Elon Osen"',
  'male',
  '16',
  '0',
  '0',
  '7534',
  '9.2167',
  '',
  'S\n'],
 ['140',
  '0',
  '1',
  '"Mr. Victor Giglio"',
  'male',
  '24',
  '0',
  '0',
  'PC 17593',
  '79.2',
  'B86',
  'C\n'],
 ['141',
  '0',
  '3',
  '"Mrs. Joseph (Sultana) Boulos"',
  'female',
  '',
  '0',
  '2',
  '2678',
  '15.2458',
  '',
  'C\n'],
 ['142',
  '1',
  '3',
  '"Miss. Anna Sofia Nysten"',
  'female',
  '22',
  '0',
  '0',
  '347081',
  '7.75',
  '',
  'S\n'],
 ['143',
  '1',
  '3',
  '"Mrs. Pekka Pietari (Elin Matilda Dolck) Hakkarainen"',
  'female',
  '24',
  '1',
  '0',
  'STON/O2. 3101279',
  '15.85',
  '',
  'S\n'],
 ['144',
  '0',
  '3',
  '"Mr. Jeremiah Burke"',
  'male',
  '19',
  '0',
  '0',
  '365222',
  '6.75',
  '',
  'Q\n'],
 ['145',
  '0',
  '2',
  '"Mr. Edgardo Samuel Andrew"',
  'male',
  '18',
  '0',
  '0',
  '231945',
  '11.5',
  '',
  'S\n'],
 ['146',
  '0',
  '2',
  '"Mr. Joseph Charles Nicholls"',
  'male',
  '19',
  '1',
  '1',
  'C.A. 33112',
  '36.75',
  '',
  'S\n'],
 ['147',
  '1',
  '3',
  '"Mr. August Edvard ("Wennerstrom") Andersson"',
  'male',
  '27',
  '0',
  '0',
  '350043',
  '7.7958',
  '',
  'S\n'],
 ['148',
  '0',
  '3',
  '"Miss. Robina Maggie "Ruby" Ford"',
  'female',
  '9',
  '2',
  '2',
  'W./C. 6608',
  '34.375',
  '',
  'S\n'],
 ['149',
  '0',
  '2',
  '"Mr. Michel ("Louis M Hoffman") Navratil"',
  'male',
  '36.5',
  '0',
  '2',
  '230080',
  '26',
  'F2',
  'S\n'],
 ['150',
  '0',
  '2',
  '"Rev. Thomas Roussel Davids Byles"',
  'male',
  '42',
  '0',
  '0',
  '244310',
  '13',
  '',
  'S\n'],
 ['151',
  '0',
  '2',
  '"Rev. Robert James Bateman"',
  'male',
  '51',
  '0',
  '0',
  'S.O.P. 1166',
  '12.525',
  '',
  'S\n'],
 ['152',
  '1',
  '1',
  '"Mrs. Thomas (Edith Wearne) Pears"',
  'female',
  '22',
  '1',
  '0',
  '113776',
  '66.6',
  'C2',
  'S\n'],
 ['153',
  '0',
  '3',
  '"Mr. Alfonzo Meo"',
  'male',
  '55.5',
  '0',
  '0',
  'A.5. 11206',
  '8.05',
  '',
  'S\n'],
 ['154',
  '0',
  '3',
  '"Mr. Austin Blyler van Billiard"',
  'male',
  '40.5',
  '0',
  '2',
  'A/5. 851',
  '14.5',
  '',
  'S\n'],
 ['155',
  '0',
  '3',

In [8]:
#dando um "join" da dataList com o dict cabeçalho 
for passenger in dataList:
    for i, info in enumerate(passenger):
        titanicInfo[header[i]].append(info)

In [31]:
#imprime todos os nomes apartir do dicionario
for data in titanicInfo["Name"]:
    print(data)

"Mr. Owen Harris Braund"
"Mrs. John Bradley (Florence Briggs Thayer) Cumings"
"Miss. Laina Heikkinen"
"Mrs. Jacques Heath (Lily May Peel) Futrelle"
"Mr. William Henry Allen"
"Mr. James Moran"
"Mr. Timothy J McCarthy"
"Master. Gosta Leonard Palsson"
"Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson"
"Mrs. Nicholas (Adele Achem) Nasser"
"Miss. Marguerite Rut Sandstrom"
"Miss. Elizabeth Bonnell"
"Mr. William Henry Saundercock"
"Mr. Anders Johan Andersson"
"Miss. Hulda Amanda Adolfina Vestrom"
"Mrs. (Mary D Kingcome)  Hewlett"
"Master. Eugene Rice"
"Mr. Charles Eugene Williams"
"Mrs. Julius (Emelia Maria Vandemoortele) Vander Planke"
"Mrs. Fatima Masselmani"
"Mr. Joseph J Fynney"
"Mr. Lawrence Beesley"
"Miss. Anna "Annie" McGowan"
"Mr. William Thompson Sloper"
"Miss. Torborg Danira Palsson"
"Mrs. Carl Oscar (Selma Augusta Emilia Johansson) Asplund"
"Mr. Farred Chehab Emir"
"Mr. Charles Alexander Fortune"
"Miss. Ellen "Nellie" O'Dwyer"
"Mr. Lalio Todoroff"
"Don. Manuel E Uruchurtu"
"Mrs. William Augustus (Marie Eugenie) Spencer"
"Miss. Mary Agatha Glynn"
"Mr. Edward H Wheadon"
"Mr. Edgar Joseph Meyer"
"Mr. Alexander Oskar Holverson"
"Mr. Hanna Mamee"
"Mr. Ernest Charles Cann"
"Miss. Augusta Maria Vander Planke"
"Miss. Jamila Nicola-Yarred"
"Mrs. Johan (Johanna Persdotter Larsson) Ahlin"
"Mrs. William John Robert (Dorothy Ann Wonnacott) Turpin"
"Mr. Theodor Kraeff"
"Miss. Simonne Marie Anne Andree Laroche"
"Miss. Margaret Delia Devaney"
"Mr. William John Rogers"
"Mr. Denis Lennon"
"Miss. Bridget O'Driscoll"
"Mr. Youssef Samaan"
"Mrs. Josef (Josefine Franchi) Arnold-Franchi"
"Master. Juha Niilo Panula"
"Mr. Richard Cater Nosworthy"
"Mrs. Henry Sleeper (Myna Haxtun) Harper"
"Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe"
"Mr. Engelhart Cornelius Ostby"
"Mr. Hugh Woolner"
"Miss. Emily Rugg"
"Mr. Mansouer Novel"
"Miss. Constance Mirium West"
"Master. William Frederick Goodwin"
"Mr. Orsen Sirayanian"
"Miss. Amelie Icard"
"Mr. Henry Birkhardt Harris"
"Master. Harald Skoog"
"Mr. Albert A Stewart"
"Master. Gerios Moubarek"
"Mrs. (Elizabeth Ramell) Nye"
"Mr. Ernest James Crease"
"Miss. Erna Alexandra Andersson"
"Mr. Vincenz Kink"
"Mr. Stephen Curnow Jenkin"
"Miss. Lillian Amy Goodwin"
"Mr. Ambrose Jr Hood"
"Mr. Apostolos Chronopoulos"
"Mr. Lee Bing"
"Mr. Sigurd Hansen Moen"
"Mr. Ivan Staneff"
"Mr. Rahamin Haim Moutal"
"Master. Alden Gates Caldwell"
"Miss. Elizabeth Dowdell"
"Mr. Achille Waelens"
"Mr. Jan Baptist Sheerlinck"
"Miss. Brigdet Delia McDermott"
"Mr. Francisco M Carrau"
"Miss. Bertha Ilett"
"Mrs. Karl Alfred (Maria Mathilda Gustafsson) Backstrom"
"Mr. William Neal Ford"
"Mr. Selman Francis Slocovski"
"Miss. Mabel Helen Fortune"
"Mr. Francesco Celotti"
"Mr. Emil Christmann"
"Mr. Paul Edvin Andreasson"
"Mr. Herbert Fuller Chaffee"
"Mr. Bertram Frank Dean"
"Mr. Daniel Coxon"
"Mr. Charles Joseph Shorney"
"Mr. George B Goldschmidt"
"Mr. William Bertram Greenfield"
"Mrs. John T (Ada Julia Bone) Doling"
"Mr. Sinai Kantor"
"Miss. Matilda Petranec"
"Mr. Pastcho ("Pentcho") Petroff"
"Mr. Richard Frasar White"
"Mr. Gustaf Joel Johansson"
"Mr. Anders Vilhelm Gustafsson"
"Mr. Stoytcho Mionoff"
"Miss. Anna Kristine Salkjelsvik"
"Mr. Albert Johan Moss"
"Mr. Tido Rekic"
"Miss. Bertha Moran"
"Mr. Walter Chamberlain Porter"
"Miss. Hileni Zabour"
"Mr. David John Barton"
"Miss. Katriina Jussila"
"Miss. Malake Attalah"
"Mr. Edvard Pekoniemi"
"Mr. Patrick Connors"
"Mr. William John Robert Turpin"
"Mr. Quigg Edmond Baxter"
"Miss. Ellis Anna Maria Andersson"
"Mr. Stanley George Hickman"
"Mr. Leonard Charles Moore"
"Mr. Nicholas Nasser"
"Miss. Susan Webber"
"Mr. Percival Wayland White"
"Master. Elias Nicola-Yarred"
"Mr. Martin McMahon"
"Mr. Fridtjof Arne Madsen"
"Miss. Anna Peter"
"Mr. Johan Ekstrom"
"Mr. Jozef Drazenoic"
"Mr. Domingos Fernandeo Coelho"
"Mrs. Alexander A (Grace Charity Laury) Robins"
"Mrs. Leopold (Mathilde Francoise Pede) Weisz"
"Mr. Samuel James Hayden Sobey"
"Mr. Emile Richard"
"Miss. Helen Monypeny Newsom"
"Mr. Jacques Heath Futrelle"
"Mr. Olaf Elon Osen"
"Mr. Victor Giglio"
"Mrs. Joseph (Sultana) Boulos"
"Miss. Anna Sofia Nysten"
"Mrs. Pekka Pietari (Elin Matilda Dolck) Hakkarainen"
"Mr. Jeremiah Burke"
"Mr. Edgardo Samuel Andrew"
"Mr. Joseph Charles Nicholls"
"Mr. August Edvard ("Wennerstrom") Andersson"
"Miss. Robina Maggie "Ruby" Ford"
"Mr. Michel ("Louis M Hoffman") Navratil"
"Rev. Thomas Roussel Davids Byles"
"Rev. Robert James Bateman"
"Mrs. Thomas (Edith Wearne) Pears"
"Mr. Alfonzo Meo"
"Mr. Austin Blyler van Billiard"
"Mr. Ole Martin Olsen"
"Mr. Charles Duane Williams"

In [9]:
#imprime todas as idades
for data in titanicInfo["Age"]:
    print(data)

22
38
26
35
35

54
2
27
14
4
58
20
39
14
55
2

31

35
34
15
28
8
38

19


40


66
28
42

21
18
14
40
27

3
19




18
7
21
49
29
65

21
28.5
5
11
22
38
45
4


29
19
17
26
32
16
21
26
32
25


0.83
30
22
29

28
17
33
16

23
24
29
20
46
26
59

71
23
34
34
28

21
33
37
28
21

38

47
14.5
22
20
17
21
70.5
29
24
2
21

32.5
32.5
54
12

24

45
33
20
47
29
25
23
19
37
16
24

22
24
19
18
19
27
9
36.5
42
51
22
55.5
40.5

51

In [10]:
#trando idades "vazias" e convertendo para tipo numerico
for i, age in enumerate(titanicInfo["Age"]):
    if titanicInfo["Age"][i] != '':
        titanicInfo["Age"][i] = float(age)
    else:
        titanicInfo["Age"][i] = -1

In [11]:
#imprime todas as idades
for data in titanicInfo["Age"]:
    print(data)

22.0
38.0
26.0
35.0
35.0
-1
54.0
2.0
27.0
14.0
4.0
58.0
20.0
39.0
14.0
55.0
2.0
-1
31.0
-1
35.0
34.0
15.0
28.0
8.0
38.0
-1
19.0
-1
-1
40.0
-1
-1
66.0
28.0
42.0
-1
21.0
18.0
14.0
40.0
27.0
-1
3.0
19.0
-1
-1
-1
-1
18.0
7.0
21.0
49.0
29.0
65.0
-1
21.0
28.5
5.0
11.0
22.0
38.0
45.0
4.0
-1
-1
29.0
19.0
17.0
26.0
32.0
16.0
21.0
26.0
32.0
25.0
-1
-1
0.83
30.0
22.0
29.0
-1
28.0
17.0
33.0
16.0
-1
23.0
24.0
29.0
20.0
46.0
26.0
59.0
-1
71.0
23.0
34.0
34.0
28.0
-1
21.0
33.0
37.0
28.0
21.0
-1
38.0
-1
47.0
14.5
22.0
20.0
17.0
21.0
70.5
29.0
24.0
2.0
21.0
-1
32.5
32.5
54.0
12.0
-1
24.0
-1
45.0
33.0
20.0
47.0
29.0
25.0
23.0
19.0
37.0
16.0
24.0
-1
22.0
24.0
19.0
18.0
19.0
27.0
9.0
36.5
42.0
51.0
22.0
55.5
40.5
-1
51.0

In [12]:
#lista com idades válidas
ageList = []
for age in titanicInfo["Age"]:
    if age != -1:
        ageList.append(age)

In [13]:
#função pra tirar média
def avg(listNumbers):
    return sum(listNumbers)/len(listNumbers)

In [14]:
#media de idades
avgAges = avg(ageList)
print(avgAges)

28.141507936507935

In [15]:
#substituindo idades inválidar para válidas
for i, age in enumerate(titanicInfo["Age"]):
    if age == -1:
        titanicInfo["Age"][i] = avgAges

In [16]:
#imprime todas as idades ATUALIZADAS
for data in titanicInfo["Age"]:
    print(data)

22.0
38.0
26.0
35.0
35.0
28.141507936507935
54.0
2.0
27.0
14.0
4.0
58.0
20.0
39.0
14.0
55.0
2.0
28.141507936507935
31.0
28.141507936507935
35.0
34.0
15.0
28.0
8.0
38.0
28.141507936507935
19.0
28.141507936507935
28.141507936507935
40.0
28.141507936507935
28.141507936507935
66.0
28.0
42.0
28.141507936507935
21.0
18.0
14.0
40.0
27.0
28.141507936507935
3.0
19.0
28.141507936507935
28.141507936507935
28.141507936507935
28.141507936507935
18.0
7.0
21.0
49.0
29.0
65.0
28.141507936507935
21.0
28.5
5.0
11.0
22.0
38.0
45.0
4.0
28.141507936507935
28.141507936507935
29.0
19.0
17.0
26.0
32.0
16.0
21.0
26.0
32.0
25.0
28.141507936507935
28.141507936507935
0.83
30.0
22.0
29.0
28.141507936507935
28.0
17.0
33.0
16.0
28.141507936507935
23.0
24.0
29.0
20.0
46.0
26.0
59.0
28.141507936507935
71.0
23.0
34.0
34.0
28.0
28.141507936507935
21.0
33.0
37.0
28.0
21.0
28.141507936507935
38.0
28.141507936507935
47.0
14.5
22.0
20.0
17.0
21.0
70.5
29.0
24.0
2.0
21.0
28.141507936507935
32.5
32.5
54.0
12.0
28.141507936507935
24.0
28.141507936507935
45.0
33.0
20.0
47.0
29.0
25.0
23.0
19.0
37.0
16.0
24.0
28.141507936507935
22.0
24.0
19.0
18.0
19.0
27.0
9.0
36.5
42.0
51.0
22.0
55.5
40.5
28.141507936507935
51.0